version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mysql
      - php
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html:delegated
      # xdebug
      - ./dockerfiles/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  mysql:
    platform: linux/x86_64 # M1チップ対応のため追記
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file:
      - ./env/mysql.env
    volumes:
      - data1:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./app:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./app:/var/www/html

volumes:
  data1:
